// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXVv52gVbzM3m52yVBhcBjeUakQ497QhM',
    appId: '1:985163900623:web:dc1a0935c2242771a479ba',
    messagingSenderId: '985163900623',
    projectId: 'pure-313e7',
    authDomain: 'pure-313e7.firebaseapp.com',
    storageBucket: 'pure-313e7.appspot.com',
    measurementId: 'G-PDMBGZE7DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCWzU8ZxNOl-e_NRCpJZ61jnfcrNMImxo',
    appId: '1:985163900623:android:f20548d755253ff3a479ba',
    messagingSenderId: '985163900623',
    projectId: 'pure-313e7',
    storageBucket: 'pure-313e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0_49Vc-5VWxt7_ZrPqAiLEoRzxpRD6Og',
    appId: '1:985163900623:ios:fc186e02dc9d5f36a479ba',
    messagingSenderId: '985163900623',
    projectId: 'pure-313e7',
    storageBucket: 'pure-313e7.appspot.com',
    iosBundleId: 'com.example.flutter03Mingflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0_49Vc-5VWxt7_ZrPqAiLEoRzxpRD6Og',
    appId: '1:985163900623:ios:fc186e02dc9d5f36a479ba',
    messagingSenderId: '985163900623',
    projectId: 'pure-313e7',
    storageBucket: 'pure-313e7.appspot.com',
    iosBundleId: 'com.example.flutter03Mingflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXVv52gVbzM3m52yVBhcBjeUakQ497QhM',
    appId: '1:985163900623:web:e2d8ef6be91a7f1aa479ba',
    messagingSenderId: '985163900623',
    projectId: 'pure-313e7',
    authDomain: 'pure-313e7.firebaseapp.com',
    storageBucket: 'pure-313e7.appspot.com',
    measurementId: 'G-L2DB353C87',
  );
}
